import Chess from "../../../../assets/DeveloperProj/Screenshot 2021-05-05 134417.png";
import MovieStreamApp from "../../../../assets/DeveloperProj/MovieStreamApp.png";
import CartImg from "../../../../assets/DesignProj/icons8-fast-cart-64.png";
import ChatRoomIcon from "../../../../assets/DeveloperProj/icons8-chat-room-100.png";

export const projectsData = [
  {
    className: "landscapeProj movieStreamProj",
    data: "fade-up",
    delay: "400",
    duration: "1000",
    link: "https://rozen2007.github.io/Chess_game/",
    Img: Chess,
    altText: "Chess-Game",
    text: "",
    innerClass: "imgWrapper",
    innerdata: "",
    innerduration: "",
    innerdelay: "",
    imgTextClass: "hideInfo",
  },
  {
    className: "leftProj",
    data: "fade-right",
    delay: "300",
    duration: "700",
    link: "https://chatting-app-1f237.web.app/",
    altText: "Covid-Tracker Image",
    text: "Chat Room App",
    Img: ChatRoomIcon,
    altText: "Chat Room App Image",
    innerTextClass: "titleHead portfoliodesign",
    innerClass: "imgWrapper",
    innerdata: "",
    innerduration: "",
    innerdelay: "",
  },
  {
    className: "rightProj",
    data: "fade-left",
    delay: "300",
    duration: "700",
    link: "https://lively-brook-3373.on.fleek.co/",
    Img: CartImg,
    altText: "Ecommerce App Image",
    text: "Ecommerce App",
    altText: "Ecommerce App Image",
    innerTextClass: "titleHead",
    innerClass: "imgWrapper",
    innerdata: "",
    innerduration: "",
    innerdelay: "",
  },
  {
    className: "landscapeProj coviddesign",
    data: "fade-up",
    delay: "750",
    duration: "1000",
    link: "https://freeeanime.herokuapp.com/",
    Img: MovieStreamApp,
    altText: "AnimeStreamWebsite",
    text:  "AnimeStreamWebsite",
    altText: "Stream App Image",
    innerTextClass: "titleHead",
    innerClass: "imgWrapper",
    innerdata: "",
    innerduration: "",
    innerdelay: "",
  },
  {
    className: "rightProj",
    data: "fade-left",
    delay: "300",
    duration: "700",
    link: "https://lively-brook-3373.on.fleek.co/",
    Img: CartImg,
    altText: "Walk & listen",
    text: "Walk & listen",
    altText: "Walk & listen",
    innerTextClass: "titleHead",
    innerClass: "imgWrapper",
    innerdata: "",
    innerduration: "",
    innerdelay: "",
  },
];
